version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MARIADB_DATABASE: chomchob
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE: "chomchob"
      DATABASE_TYPE: "mariadb"